# Site Settings
title: My Resume
url: 'http://libaiw.github.io'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Mike Lee
tagline: Data Intelligence Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'
summary: '<B>Technology Innovation Leader</B>,  Exploiting emerging technologies like DI(Data Intelligence), IoT (Internet of Thing), Machine Learning to build Business Intelligence, Cloud / BigData Marketing solutions & Data analysis.<br>
<B>Custom Development</B>, Leading team to leverage full lifecycle Software development services using a wide variety of technologies. Been committed to customer’s success with eagerly digging deeper to understand customer’s business essence. Developing varieties of projects with planning, orchestrated execution, and constant communication.<br> 
Hold the reputation as <B>"problem solver for both technology and business"</B>, Proven success in building top-performing technology team that thrive on continuous learning, embrace creativity and excel through innovation.
'


#sidebar links
email: libaiw@gmail.com
phone: 857 233 6267
website: libaiw.github.io/blogger/ #do not add http://
linkedin: mike-li-02a327103
github: libaiw
twitter: '@libaiw'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
